/** Audit actions; extend as modules land (PRD FR-AUD-02). */
export const auditActions = [
  "auth.login.succeeded",
  "auth.login.failed",
  "auth.login.locked",
  "auth.logout",
  "auth.pin.changed",
  "auth.password.changed",
  "auth.password.recovered",
  "auth.password.recovery-failed",
  "auth.password.reset",
  "auth.recovery-codes.generated",
  "auth.session.ended",
  "role.created",
  "role.updated",
  "role.activated",
  "role.deactivated",
  "employee.created",
  "employee.updated",
  "employee.activated",
  "employee.deactivated",
  "employee.pin.reset",
  "settings.updated",
  "bank-account.created",
  "bank-account.updated",
  "bank-account.activated",
  "bank-account.deactivated",
  "bank-account.qris-set",
  "bank-account.qris-cleared",
  "marketplace.created",
  "marketplace.updated",
  "marketplace.activated",
  "marketplace.deactivated",
  "category.created",
  "category.updated",
  "category.deleted",
  "brand.created",
  "brand.updated",
  "brand.deleted",
  "product.created",
  "product.updated",
  "product.activated",
  "product.deactivated",
  "stock.moved",
  "stock.minimum-set",
  "audit.exported",
  "audit.purged",
  "product.variants-enabled",
  "variant.created",
  "variant.updated",
  "variant.activated",
  "variant.deactivated",
  "variant.reordered",
  "shift.opened",
  "shift.closed",
  "sale.completed",
  "sale.voided",
  "approval.requested",
  "approval.auto-approved",
  "approval.approved",
  "approval.rejected",
  "approval.cancelled",
  "voucher.revision-approved",
  "voucher.activated",
  "voucher.deactivated",
  "kasbon.opened",
  "kasbon.payment-recorded",
  "kasbon.payment-approved",
  "online-order.created",
  "online-order.status-changed",
  "housekeeping.exported",
  "housekeeping.archived",
  "consignment.taken",
  "consignment.settled",
  "stock.cut",
  "expense.recorded",
  "deposit.recorded",
  "deposit.edited",
  "deposit.cancelled",
] as const;

export type AuditAction = (typeof auditActions)[number];

/** Message key under `Audit.actions`; next-intl reserves `.` for nesting. */
export function auditActionMessageKey(action: AuditAction): string {
  return action.replace(/\./g, "_");
}
